example-voting-app-vote:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: vote.pro.harbur.io
        paths:
        - /
    tls:
    - secretName: vote.pro.harbur.io-tls
      hosts:
      - vote.pro.harbur.io

example-voting-app-result:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: result.pro.harbur.io
        paths:
        - /
    tls:
    - secretName: result.pro.harbur.io-tls
      hosts:
      - result.pro.harbur.io

redis:
  master:
    persistence:
      size: 100Mi
  slave:
    persistence:
      size: 100Mi

postgresql:
  persistence:
    size: 100Mi
